name: CI/CD for AWS CDK Inference Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'cdk/**'
      - 'lambda/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-west-2

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r cdk/requirements.txt
          pip install flake8 pytest aws-cdk-lib constructs

      - name: Lint code
        run: flake8 cdk/ || true

      - name: Run tests
        run: |
          if [ -d "cdk/tests" ]; then
            pytest cdk/tests/
          else
            echo "No tests found"
          fi

      - name: CDK synth
        run: |
          cd cdk
          npx aws-cdk synth

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://yourapp.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r cdk/requirements.txt
          pip install aws-cdk-lib constructs

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK deploy
        run: |
          cd cdk
          cdk deploy --require-approval never
