name: Deploy AWS Infrastructure via CDK

on:
  push:
    branches: [main]
    paths:
      - 'cdk/**'
      - 'lambda/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2  # change to your AWS region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cdk/requirements.txt
          pip install -r lambda/requirements.txt
          pip install flake8 pytest aws-cdk-lib constructs

      - name: Lint Python code
        run: |
          flake8 lambda/ cdk/ --max-line-length=120

      - name: Run unit tests
        run: |
          pytest lambda/tests/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK synth
        run: |
          cd cdk
          cdk synth

      - name: CDK deploy
        run: |
          cd cdk
          cdk deploy --require-approval never
